# Generated by Django 4.2.6 on 2023-11-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingblog',
            name='recipe_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
